[IV-21-22] Objetivo 2
Pablont98/IV pull request #11
Opened 2021-10-20 09:32 UTC by vlljuan99

Cuando se realice el merge de este PR se cerrarán los issues #9 , #12 , #13 

closes #9 
closes #12 
closes #13

2021-10-20 09:58 UTC, vlljuan99 commented
@Pablont98 asocia los issues #9 , #12 , #13  al [milestone 1](https://github.com/Pablont98/IV/milestone/1), por favor.

Debería estar listo para la comprobación.

2021-10-21 00:19 UTC, Pablont98 commented
Por favor, arregla lo que he comentado mas arriba. Un saludo

2021-10-21 00:36 UTC, vlljuan99 commented
> Por favor, arregla lo que he comentado mas arriba. Un saludo

Pablo disculpa pero no veo los comentarios, ¿Dónde están?

2021-10-21 07:36 UTC, Pablont98 requested changes
* Creas atributos de clase y de instancia y las declaras con el mismo nombre. ¿Para que sirven las variables de clase aquí? ¿Qué sentido tiene?
* No añades ningún método (funcionalidad) a la clase.

2021-10-21 07:36 UTC, Pablont98 commented on src/Ingrediente.py
> +
Aquí haces lo mismo. 

* Creas atributos de clase y de instancia y las declaras con el mismo nombre. ¿Para que sirven las variables de clase aquí? ¿Qué sentido tiene?
* No añades ningún método (funcionalidad) a la clase.

2021-10-21 08:34 UTC, vlljuan99 commented
> * Creas atributos de clase y de instancia y las declaras con el mismo nombre. ¿Para que sirven las variables de clase aquí? ¿Qué sentido tiene?
> * No añades ningún método (funcionalidad) a la clase.

Fallos corregidos. No sé si debería haber implementado el método de calcular las kcals totales, pero como era muy básico lo he puesto.

2021-10-21 10:27 UTC, Pablont98 submitted a review, later dismissed
* Los métodos get en python de un atributo de instancia no son necesarios. Por lo que no se ponen.
* Los comentarios hechos entre ''' ''' (docstrings) se ponen debajo de la  declaración del método.
* En este objetivo no era necesario implementar ninguno de los métodos. Basta con declararlos, añadir un comentario si se estima oportuno y añadir un "pass". No obstante ya puedes dejar la implementación del método "kcals_maximas" de Receta.py. Solo te lo comento para que cuando añadas un método válido en Ingrediente.py no te calientes la cabeza añadiendo la funcionalidad del método y solo pongas el comentario que explique que hace el método y un "pass".

2021-10-22 11:57 UTC, vlljuan99 commented
He corregido ambos archivos.

2021-10-22 18:08 UTC, Pablont98 commented
Listo para revisión @JJ

2021-10-24 07:18 UTC, JJ requested changes
Bastante minimalista y con un desarrollo bien dirigido. El problema es que eventualmente habéis creado clases que tienen errores porque habéis perdido de vista la lógica de negocio.

2021-10-24 07:18 UTC, JJ commented on iv.yaml
> +entidad: /src/Receta.py
Este path absoluto está mal y va a dar error más adelante.

2021-10-24 07:18 UTC, JJ commented on src/Receta.py
> +                kcals += ing.kcals
Entonces, si una receta tiene "patatas", ¿siempre tiene la misma cantidad de calorías?

2021-10-24 08:58 UTC, Pablont98 commented
Con lo comentado por el profesor sería interesante: 
* Crear un atributo "unidad" para diferenciar entre gramos, litros, etc
* Crear un atributo "cantidad" en la clase ingrediente (Por ejemplo la cantidad podría corresponder a gramos, aunque vendrá dado por el atributo unidad).
* Cambiar el atributo "kcals" por "kcals_base" en la clase ingrediente. Donde kcals_base sea el numero de kcals por una cantidad preestablecida (Ejemplo 1 kcal por 100g de ingrediente)
* Crear un método en la clase ingrediente el cual nos de las kcals totales con respecto a la cantidad del ingrediente.

Con esto se podría solucionar el inconveniente.

2021-10-25 17:34 UTC, vlljuan99 commented
> Con lo comentado por el profesor sería interesante:
> 
> * Crear un atributo "unidad" para diferenciar entre gramos, litros, etc
> * Crear un atributo "cantidad" en la clase ingrediente (Por ejemplo la cantidad podría corresponder a gramos, aunque vendrá dado por el atributo unidad).
> * Cambiar el atributo "kcals" por "kcals_base" en la clase ingrediente. Donde kcals_base sea el numero de kcals por una cantidad preestablecida (Ejemplo 1 kcal por 100g de ingrediente)
> * Crear un método en la clase ingrediente el cual nos de las kcals totales con respecto a la cantidad del ingrediente.
> 
> Con esto se podría solucionar el inconveniente.

Ok, he introducido los cambios que me has pedido.

2021-10-25 17:54 UTC, Pablont98 commented
Listo para revisión @JJ

2021-10-27 05:56 UTC, JJ approved these changes
Esencialmente, este objetivo está alcanzado, lo que ocurre es que el código está mal y aunque esté aceptado por mi parte el product manager no debería hacerlo
1. El código de Ingrediente incluye una función que ni está relacionada con la lógica de negocio ni da pistas sobre qué es lo que hace
2. El código de receta incluye código que no se pide en este PMV, y que además está mal. No se ha hecho nada sobre el comentario que se puso.

2021-10-27 11:04 UTC, Pablont98 commented
> Esencialmente, este objetivo está alcanzado, lo que ocurre es que el código está mal y aunque esté aceptado por mi parte el product manager no debería hacerlo
> 
>     1. El código de Ingrediente incluye una función que ni está relacionada con la lógica de negocio ni da pistas sobre qué es lo que hace
> 
>     2. El código de receta incluye código que no se pide en este PMV, y que además está mal. No se ha hecho nada sobre el comentario que se puso.

@JJ Considero que el método de la clase ingrediente si tiene una funcionalidad válida para el proyecto, facilitará en cierta medida el calculo de calorías totales de la receta resultante. @vlljuan99 Deberías comentar la funcionalidad de dicho método a la par que deberías borrar los "= None" de los métodos __init__. Por último, borra el código referente al método del calculo de calorías máximas en la clase Receta y en su lugar pon un "pass".

2021-10-27 14:55 UTC, vlljuan99 commented
Correcciones hechas

2021-10-27 17:06 UTC, merged