IV-21-22 Objetivo 4
Pablont98/IV pull request #19
Opened 2021-11-06 11:55 UTC by Pablont98

### PR referente al objetivo 4 de la asignatura IV 21-22 ###

Se ha trabajado en las funcionalidades de la clase Receta para el cálculo de la información nutricional de esta. ([Issue 
[HU4] Cálculo de información nutricional de una receta](#17)). Resolviendo así dicho [HU4]

Información de la clase que se va a testear [aquí](https://github.com/Pablont98/IV/blob/Objetivo-4/docs/InformacionReceta.md).
Justificación de uso de pytest [aquí](https://github.com/Pablont98/IV/blob/Objetivo-4/docs/justificacion_pytest.md).

Se han añadido cambios a los .py del directorio src:
* Cambios de [Ingrediente.py](https://github.com/Pablont98/IV/blob/Objetivo-4/src/Ingrediente.py): Se han añadido a los ingredientes los atributos: hidratos, proteínas y grasas, y sus respectivos métodos de cálculo de sus valores en relación a su cantidad
* Cambios de [Receta.py](https://github.com/Pablont98/IV/blob/Objetivo-4/src/Ingrediente.py): Se han añadido los respectivos métodos para el cálculo máximo de hidratos, proteínas y grasas de la receta, ademas de añadir un método para visualizar la receta en forma de carta (no es importante para la funcionalidad del proyecto, pero personalmente me hacía el trabajo mas visual)

Acceso al archivo de test [aquí](https://github.com/Pablont98/IV/blob/Objetivo-4/test/test_receta.py).

Al cerrarse este PR se cerrará el issue #17 ya que se considerá que la funcionalidad que se pide en dicho issue se cumple (demostrable con los test)
closes #17

2021-11-06 12:48 UTC, Pablont98 commented
@JJ listo para revisión.

2021-11-09 12:02 UTC, JJ requested changes
Mejor que antes, pero
* No sigues el formato estándar de los mensajes de commit. Tampoco puede ser "añadidas funcionalidades". Tienes que explicar cómo solucionas un problema.
* No puedes cerrar una HU. "El programa" no va a ofrecer nada con el cálculo. Tendrás que esperar al frontend.
* No puedes desarrollar una HU directamjetne, tiene que haber issues por medio (asignados a un milestone)
* Casi ninguno de los commits está hecho desde una configuración correcta, porque no tienes configurado tu usuario localmente.

En este caso, como en el anterior, lo mejor es cerrar y empezar desde cero, porque los commits que están mal no van a mejorar. Como segunda aproximación, haz el desarrollo correctamente y los commits que se refieran a los nuevos issues hazlos también correctamente.

2021-11-09 12:20 UTC, Pablont98 commented
Vale, entonces borre mi enlace de este PR de su repositorio y volveré a hacer otro PR nuevo siguiendo las indicaciones que me ha marcado.

2021-11-09 12:21 UTC, JJ commented
Puedes añadir otro nuevo pisando el que hay, ya pasará los tests en ese caso.

2021-11-09 12:22 UTC, Pablont98 commented
Perfecto, pues cierro este PR

2021-11-09 19:37 UTC, closed without merging