IV-21-22 Objetivo-5
Pablont98/IV pull request #38
Opened 2021-11-19 18:31 UTC by Pablont98

PR en desarrollo ...

2021-11-19 19:54 UTC, Pablont98 commented
@JJ listo para revisión.

2021-11-20 13:16 UTC, JJ requested changes
Como ya es el tercero que tiene el contenedor de Python 3.8, no vas a pasar el objetivo para que os curréis un poco más la búsqueda del contenedor base en vez de poner todos el misom (y poner razones espurias como "es el que usa mi proyecto"). El contenedor de test tiene que tener la versión de Python con la que quieres testear tu proyecto, y esto tiene que ser una decisión que se tome en un issue.

2021-11-20 13:16 UTC, JJ commented on .github/workflows/build.yml
> +    branches:
Esto genera el Dockerfile siempre

2021-11-20 16:08 UTC, Pablont98 commented on .github/workflows/build.yml
> +    branches:
No entiendo lo que quiere decir

2021-11-21 09:14 UTC, JJ commented on .github/workflows/build.yml
> +    branches:
¿Para qué sirve on? ¿Lo estás usando para que genere la imagen sólo cuando cambia el Dockerfile?

2021-11-21 10:31 UTC, Pablont98 commented on .github/workflows/build.yml
> +    branches:
Con eso hago que los jobs se ejecuten cuando se sube un cambio al repositorio. no?

2021-11-22 11:49 UTC, Pablont98 commented
Cambiado contenedor base, puede verlo [aquí](https://github.com/Pablont98/recetas-iv/blob/Objetivo-5/README.md)

@JJ listo para revisión.

2021-11-22 11:55 UTC, JJ approved these changes
:+1:

2021-11-22 11:55 UTC, JJ commented on .github/workflows/sync.yml
> +      - main
Si cambia sólo el README, ¿por qué no haces que se lance sólo cuando cambia?
Eso es cosa del otro objetivo, igual que arriba, así que mejor dejarlo.

2021-11-25 17:45 UTC, merged