Objetivo 1
Pablont98/IV pull request #8
Opened 2021-09-25 09:14 UTC by Pablont98

Pull request referente al objetivo 1

2021-09-25 09:41 UTC, JJ requested changes
Realmente has alcanzado la mayor parte del objetivo la has alcanzado. Hay algunas objeciones (indicadas). Aparte de lo indicado, problemas menores
1. Los hitos son descripciones de productos, no descripciones de actividades como "crear"
2. Debes intentar que los mensajes de commits sean informativos, Es una buena práctica común, y "update README.md" no informan de nada.
3. La documentación no está en el Pull request, pero sí en una rama que se llama de la misma forma. O hay algún espacio en blanco por algún lado, o algo raro pasa.
4. Mira la chuleta de GitHub para hacer el documento correctamente, en vez de todo en negrita.
5. Corrige errores tipográficos (como apss)
El problema principal, de todas formas, está en las historias de usuario. Estas deben cubrir de forma bastante completa el dominio del problema, y tratar de definir (en ellas o en algún lado) todos los términos de la misma. Por ejemplo, alguna historia de usuario debe incluir el concepto "dieta" o incluso "receta". Si no lo incluyes, ¿cómo vas a poder implementarlo?

2021-09-25 09:41 UTC, JJ commented on README.md
> +una pagina en la consultar recetas.
Por favor, corrige los errores tipográficos.

2021-09-25 09:41 UTC, JJ commented on README.md
>  El lenguaje a utilizar (en un principio) será Python
En esta fase no hay que incluir ningún detalle de implementación.

2021-09-25 09:41 UTC, JJ commented on README.md
> +[Documentacion de este objetivo](docs/HU.md)
La documentación debe estar también en el PR; todo lo que contribuya a cumplir el objetivo debe estar aquí.

2021-09-25 12:07 UTC, Pablont98 commented on README.md
>  El lenguaje a utilizar (en un principio) será Python
Quitado y commiteado

2021-09-25 12:08 UTC, Pablont98 commented on README.md
> +una pagina en la consultar recetas.
Corregido, ahora esta correcto esteticamente

2021-09-25 12:10 UTC, Pablont98 commented on README.md
> +[Documentacion de este objetivo](docs/HU.md)
Corregido, ahora la documentación está en el comentario del PR

2021-09-25 12:12 UTC, Pablont98 commented
Corregidos los fallos comentados (o eso creo). 
A la espera de indicaciones, un saludo.

2021-09-25 16:15 UTC, JJ commented
Tienes conflictos con tu propio repo.

2021-09-25 16:33 UTC, Pablont98 commented
Como puedo saber de que conflictos se tratan? Para solucionarlos

2021-09-25 17:35 UTC, JJ commented
¿Pinchando en un botón que pone "solve conflicts"?

2021-09-25 18:49 UTC, Pablont98 commented
Ok, no veo esa opcion porque estoy desde el movil ya que estoy trabajando. Esta noche le echaré un vistazo

2021-09-25 20:54 UTC, Pablont98 commented
No me deja pulsar la opcion "Resolve conflicts" y tampoco me ejecuta los comandos git que me recomienda hacer ...

2021-09-26 07:04 UTC, JJ commented
Pues tendrás que buscar la forma de resolverlo, desde la línea de órdenes por ejemplo, porque con conflictos no te deja fusionar.
Toma nota también de lo hecho para que se produzca el conflicto y procura no hacerlo en el futuro.

2021-09-26 08:43 UTC, Pablont98 commented
El problema estaba en que en el main estaba el directorio docs cuando cree la rama objetivo-1. Mas tarde borre el directorio docs de main para probar cosas. Ahora ya no hay conflictos. Puedo proceder a hacer Rebase and merge?

2021-09-26 09:23 UTC, JJ commented
Ya no tiene conflictos, así que arreglado.

2021-09-27 05:13 UTC, Pablont98 commented
Me da entonces permiso para hacer rebase y merge?

2021-09-27 16:51 UTC, JJ requested changes
Por favor, consulta en la web o donde estimes conveniente 
* Qué es una historia de usuario
* No he mirado los milestones, pero quizás convenga también que lo hagas.
* Qué es un producto mínimamente viable.

2021-09-27 16:51 UTC, JJ commented on README.md
> +una pagina en la consultar recetas.
"caloricas" lleva tilde.

2021-09-27 16:51 UTC, JJ commented on docs/HU.md
> +<h2 id="Titulo">Documentación correspondiente al objetivo-1</h2>
En markdown puedes poner simplemente ##

2021-09-27 16:51 UTC, JJ commented on docs/HU.md
> +* De manera invisible al usuario que utilice dicha aplicación se hará un seguimiento de lo buscado/marcado por el usuario
¿Quién sube las dietas? ¿De dónde salen las dietas?

2021-09-27 16:51 UTC, JJ commented on docs/HU.md
> +> Usuarios registrados en un intervalo de edad de 18 a 24 años buscan frecuentemente comidas con el tag "pasta" y "comida rapida"
"rapida" lleva tilde.

2021-09-27 16:51 UTC, JJ commented on docs/HU.md
> +> Usuarios registrados en un intervalo de edad de 50 a 65 años buscan frecuentemente comidas con el tag "bajas en calorias"
"calorías" lleva tilde. Por favor, usa un corrector ortográfico sobre el texto. La mayoría de los IDEs, como Emacs o Code, lo tienen.

2021-09-27 16:51 UTC, JJ commented on README.md
> +En esta aplicación se podran tanto consultar recetas de manera independiente según nuestros gustos,
"podrán" lleva tilde.

2021-09-28 10:07 UTC, Pablont98 commented
He enfocado de manera distinta el proyecto, por lo que he cambiado 2 de las HU, y algunos milestones. El usuario "casual" ha desaparecido y en su lugar están usuario alérgico y usuario estudiante.

[Documentacion de este objetivo](docs/HU.md)

2021-09-28 10:09 UTC, Pablont98 commented
Tengo un conflicto con Rebase and merge pero si puedo hacer create a merge commit. Si no encuentro manera de solucionar dicho conflicto una vez que me de el visto bueno en lo que a documentación, issues y milestones se refiere, optare por hacer create a merge commit.

2021-09-28 10:12 UTC, Pablont98 commented on docs/HU.md
> +* De manera invisible al usuario que utilice dicha aplicación se hará un seguimiento de lo buscado/marcado por el usuario
Las dietas son un conjunto de recetas que siguen unas restricciones impuestas por el propio usuario (como dice la documentación). La dieta la crea la propia aplicación a partir de las restricciones dadas por el usuario.

2021-09-28 11:16 UTC, JJ approved these changes
Te voy a aceptar el objetivo sobre todo por el esfuerzo realizado. Pero
* Los milestones son productos mínimamenbe viables. Un "algoritmo" es algo que le cuentas a alguien en un powerpoint, no un producto. Por favor, revisa eso para que hable de productos razonables.
La principal razón por la que la he aceptado es porque te has dado cuenta que lo esencial de la aplicación es empezar desarrollando la lógica de negocio. Te falta, sin embargo, que las HUs y la descripción de los milestones se adapte.

2021-09-28 11:16 UTC, JJ commented on docs/HU.md
> +# Documentación correspondiente al objetivo-1 #
Por favor, consulta la chuleta de Markdown que os di en clase.

2021-09-28 11:16 UTC, JJ commented on docs/HU.md
> +* De manera invisible al usuario que utilice dicha aplicación se hará un seguimiento de lo buscado/marcado por el usuario
OK, ¿de dónde salen los datos para las dietas?

2021-09-29 08:17 UTC, merged

2021-10-02 09:38 UTC, JJ commented
El siguiente objetivo lo llevará a cabo @vlljuan99